---
- hosts: all
  user: AbdullahTaher
 
  vars:
    project_path: /home/project/CCMYproject
  tasks:
  
    
    - name: Clone my RP
      become: yes
      git:
        
        repo: https://github.com/AbdullahTaher93/CCMYproject.git
        dest: "{{ project_path }}"
          
    - name: Instalar npm
      become: yes
      become_method: sudo
      apt:
        pkg=npm state=present
    
    

    - name: Install pm2
      become: yes
      become_method: sudo
      npm:
        name: pm2
        global: yes
    - name: delete pre RP 
      command: pm2 delete PR
      ignore_errors: yes

      - name: Redir port
      become: yes
      become_method: sudo
      command: iptables -t nat -I PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 3000

    
    - name: Arrancar pm2
      command: pm2 start {{ project_path }}/index.js --name PR
    
